# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "../packer_virtualbox-builder_virtualbox.box"
  config.ssh.username = "vagrant"

  config.vm.usable_port_range = (2200..2299)
  config.vm.network "forwarded_port", guest: 9000,    host: 2280,  auto_correct: true
end
